[application]
name = "resty_form_alpha"

[web.app]
title = "Restos"

[web.resource]
style = []
script = []

[web.watcher]
reload_html = true
watch_path = ["src", "assets", "public"]

[web.resource.dev]
script = []
